### ISSUE TITLE
Increase coverage

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#266]
There are a few places where the code isn't adequately covered. See

https://app.codecov.io/github/tskit-dev/tsdate/tree/main/tsdate

**Comment by hyanwong** [comment]
Much better now

<img width="772" alt="Screenshot 2023-06-15 at 08 36 04" src="https://github.com/tskit-dev/tsdate/assets/4699014/d8ae0544-0831-49f8-a041-a894cdd67d88">

**Comment by nspope** [comment]
Anything that's numba JIT'd won't be captured by codecov, e.g. https://community.codecov.com/t/numba-jitted-methods-are-not-captured-by-codecov/2649. For hypergeo.py and approx.py, most (all) of the functions are numba-decorated, so that explains the very low coverage there.

I think there's a way to disable JIT for the tests.

**Comment by hyanwong** [comment]
https://github.com/jeromekelleher/phylokit/issues/11
