### ISSUE TITLE
Revisit exclusion of unary regions

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#288]
If we are using a global prior, then it should be quite easy to test whether including unary regions of otherwise coalescent nodes helps (as we might hope it does). It would also be useful to check this using the variational gamma method

This is particularly easy now that you can simulate while leaving in the unary nodes, e.g. via 

```python
msprime.sim_ancestry(..., coalescing_segments_only=False)
```

For example, dating the true tree sequence, it seems to improve matters (when measured by the correlation coefficient"

```python
mu = 1e-8
rho = 1e-8
L = 1e8
Ne = 1e4
n=100

ts = msprime.sim_mutations(
    msprime.sim_ancestry(
        n,
        population_size=Ne,
        sequence_length=L,
        recombination_rate=rho,
        coalescing_segments_only=False
    ),
    rate=mu,
)
# Test with the "correct" tree sequence
prior = tsdate.build_prior_grid(ts, population_size=Ne, allow_unary=True) # can take a long time
dts = tsdate.date(ts, population_size=Ne, mutation_rate=mu)
dsimp_ts = tsdate.date(ts.simplify(), population_size=Ne, mutation_rate=mu)

use = ts.nodes_time > 0
print(
    "With unary nodes:",
    np.corrcoef(np.log(ts.nodes_time[use]), np.log(dts.nodes_time[use]))[0, 1],
)

print(
    "Unary nodes simplified away:",
    np.corrcoef(np.log(ts.nodes_time[use]), np.log(dsimp_ts.nodes_time[use]))[0, 1],
)
```

Giving

```
With unary nodes: 0.9903755167448219
Unary nodes simplified away: 0.9851946755800901
```

**Comment by hyanwong** [comment]
With an inferred tree sequence, we have the choice to either remove all unary regions or remove nodes that are entirely unary.

With the `inside-outside` method, it appears that the extra unary regions create a patch of badly overestimated times at the oldest timepoints.

![image](https://github.com/tskit-dev/tsdate/assets/4699014/7169d7cf-c749-4ec0-b07f-5d99f74aee84)

(this is reflected in the correlation coefficients of the logged node times (in this case, 0.87659 for the plot with unary portions of coalescent nodes, and 0.88356 when there are no unary regions)

I am trying to test this using the variational_gamma method, but am hitting issues (https://github.com/tskit-dev/tsdate/issues/286 and https://github.com/tskit-dev/tsdate/issues/289)

**Comment by nspope** [comment]
Here's an example with the variational gamma method applied to a simulated unary-containing tree sequence (1Mb/100 diploids), relative to the same sequence that's been simplified. In these figures I'm showing the same set of nodes (e.g. subsetting nodes in the unary TS via the `map_nodes` option to `simplify`).

<p float="left">
  <img src="https://github.com/tskit-dev/tsdate/assets/5767783/fd730d57-8abf-42c9-9b0c-03990232ec20" width="50%" />
  <img src="https://github.com/tskit-dev/tsdate/assets/5767783/258faea0-ea12-4d80-b9a7-8e30d900c0aa" width="50%" /> 
</p>

Including unary nodes improves things rather substantially in this case, but takes way longer to converge (the posteriors get very precise, so each iteration only moves them incrementally). And I'm not sure if this'll carry over to inferred tree sequences (the posteriors might concentrate strongly around the wrong answer). But, it's interesting that there's so much more information.

**Comment by hyanwong** [comment]
We also need to look into this: https://github.com/tskit-dev/tsdate/issues/110#issuecomment-734080857

**Comment by nspope** [comment]
Using the unary nodes added by `tsinfer` causes similar issues to the non-variational case. But, I've figured out why (I think). 

Here's inferred time vs level order (default time assigned by `tsinfer`) after 100 EP iterations, but before the `constrain_ages_topo` routine has been invoked: 

<img src="https://github.com/tskit-dev/tsdate/assets/5767783/087f6fa8-b39f-44c4-8816-e4bb86c9785e" width="60%">

here the point color shows the gamma shape parameters of the variational approximation, which have been capped at 1000 using #305. The curve should be monotonically increasing on average (b/c parents are older than children) -- however, it becomes non-monotonic around 0.8 on the x-axis. Moreover, these "anomalous" nodes have very high shape parameters, that would degenerate (shape go to infinity) if they weren't constrained, causing the routine to error out.

What's going on here? It turns out these are ancient nodes that span nearly the entire tree sequence (in unary form for much of it). This means that to satisfy topological constraints, they must be younger than the youngest root node but older than any other node. It turns out this is really hard to satisfy: it forces the ages of these big unary nodes to "bend" like in the attached plot. Moreover, this hard-to-satisfy constraint causes the feasible support for the approximations to concentrate to an arbitrary degree, which causes the shape parameters to go to infinity. So, the numerical errors here are actually telling us something useful about the compatibility of the tree sequence topology with the dating model.

If `constrain_ages_topo` is applied after this, it forces the ages of these unary nodes (and the root nodes) to be far older than they actually are. I think this is what is happening for the original `inside-outside` case, too (to test this, one could dump the posteriors and plot the means without applying the topology constraint -- i'd expect you'd see a 'bendy' pattern like for the variational algo).

For comparison, here's the same tree sequence after simplification (no cap on shape parameters needed here):

<img src="https://github.com/tskit-dev/tsdate/assets/5767783/835527a5-5382-4ea9-ae7a-9fb5ef89b480" width="60%">

**Comment by nspope** [comment]
I guess the takehome here is that overly-long node spans can introduce artefacts -- and including unary regions added by tsinfer allows nodes to have unrealistically large spans. A quick-and-dirty fix could be to impose a maximum length for ancestral haplotypes (maybe defined in terms of # of changes in degree rather than in BP).

**Comment by hyanwong** [comment]
Beautiful. Thanks for the analysis. This is lovely.

I wonder how long the unary sections would be if we reduced everything to coalescent-only regions, then increased them again using @petrelharp 's "extend_edges" routine?

We know that, on average, the spans of nodes should decrease as they get older, so we could set some constraints on unary regions so that the mean node span is continuously decreasing with age?

Alternatively, another approach would be to only keep unary regions when the node is more recent than a certain age, but that seems rather arbitrary.

**Comment by nspope** [comment]
I've run some small examples with unary nodes added by "extend_edges", and they don't suffer from the problem above -- the plot looks very similar to the "simplified" version above. There's definitely fewer edges (e.g. EP iterations go quicker, which is great!) But I'm not yet clear if the unary regions improve accuracy -- seems pretty close to the simplified version on the small examples I've been able to run.

Notice that the spread of the ages in the tsinfer-unary-node figure in my previous comment is much less than that of the simplified version (before things get weird). This might be an artefact, or might reflect some added information akin to what happens with simulated unary-containing ARGs. Definitely worth poking at.

**Comment by hyanwong** [comment]
> But I'm not yet clear if the unary regions improve accuracy

Probably worth looking at the same plot when redating the true topology, with and without unary nodes. You can use `msprime.sim_ancestry(..., coalescing_segments_only=False)` for this.

**Comment by hyanwong** [comment]
In #312 @petrelharp argued that we can never know, from the distribution of mutations among the samples, whether a mutation occurs above or below a unary region. If this is correct (which I think it might be), then we have an additional problem when using a tree sequence containing these regions, as we are assuming that we know which edge the mutation lies on. The example at the top of this issue, involving dating a known tree sequence containing unary regions, is misleading because in this case we are placing the mutation on the correct edge: something that would be unknowable in reality.

Solving this properly sounds complicated to me. We would need to update the node times by treating two successive edges as a single edge for the purposes of the mutational likelihood calculation, but then update the node times such that the unary regions was counted somehow.

**Comment by hyanwong** [comment]
We have come to realise that if we have the unary nodes correct, it improves accuracy, but spuriously tying nodes together can *seriously* dent accuracy and hinder convergence of the EP algorithm, so we currently recommend not only removing the unary nodes but also splitting disjoint nodes on real data. Hence I'm closing this.
