### ISSUE TITLE
unpin numba version

### ISSUE THREAD

**Issue by alxsimon** [tskit-dev/tsdate#372]
Hi, unless there is a specific compatibility reason, would it be possible to unpin the numba version?
I think this is important for distributions that are lagging behind in terms of packaging for example.

**Comment by nspope** [comment]
Unfortunately we do need to pin to a minimum version, as there's a lot of movement in numba with regards to supported numpy features. What's the packaging issue you're bumping up against?

**Comment by nspope** [comment]
Hmm, sorry! I can't remember the exact reason, but 0.58.1 was necessary for LLVM compilation to work.

**Comment by alxsimon** [comment]
How do you check LLVM compilation works? Project build and tests have been fine with version 0.56.4. I can check on my end if this is ok.

**Comment by nspope** [comment]
It was erroring out on my (and @hyanwong's) systems on import. If you're not seeing it currently, perhaps the numpy feature that triggered the error is no longer being used. But, because we're actively working on the new tsdate version, we're bound to bump up against this again ... once development has slowed down, we could revisit? 

For an existing release, if everything is importing without errors given numba 0.56.x, I think you can safely ignore the pin.

**Comment by alxsimon** [comment]
As a note for future reference, just checked and tsdate is building, testing and importing without issues under guix with 
python 3.10.7
numpy 1.23.2
numba 0.56.4
