### ISSUE TITLE
Viterbi Algorithm

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#40]
Implement viterbi algorithm

**Comment by hyanwong** [comment]
Some thoughts I've just had, @awohns:

1. I think we need to store traceback pointers for every edge in the TS (not every node).
2. We need `grid_size` traceback pointers per edge
3. Each pointer needs to indicate the hidden state of the edge.child it came from (hence we can simply store the index of the hidden state (e.g. 0..50)
4. I suggest we use 2 bytes (`np.uint16`) for these pointers, which allows up to 65536 hidden states. For UKB+TGP, which has 185 million edges, and with 50 timeslices, that means the traceback array should be 185 * 2 * 50 megabytes, or roughly 18GB, which is fine for a server. If we want 100 timeslices, it will obviously be twice that, which is still fine too.

**Comment by hyanwong** [comment]
> 4\. I suggest we use 2 bytes (`np.uint16`) for these pointers

I'm being stupid. We can decide on what size to use for the base storage depending on the grid size. For <=256 hidden states, we can use `np.uint8`, for >256 but <65536 states we can use `np.uint16`, and for anything more we can use `np.uint32` (and check that the user isn't asking for > 2^32 states!).

Since this is by far the largest use of memory in tsdate, we should perhaps think about storing it in a zarr array, so it can be disk mapped if necessary.

**Comment by awohns** [comment]
@hyanwong, is this still something we want to do?

**Comment by hyanwong** [comment]
I think we'll have problems with the loopiness. So we can drop this, but maybe we should have a "future ideas" section that we can add this sort of thing to?
