### ISSUE TITLE
Mention in docs about not making coalescent assumptions

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#425]
In contrast to many methods, the combination of tsinfer + tsdate-vgamma does not incorporate a coalescent prior (it has a improper "flat" prior on most nodes and an exponential prior on the roots, fit by EM). In other words, we are (mostly) just using mutational density (or polytomy-aware equivalent) to fit the node times. This is both a strength (not so susceptible to assumptions of demography / selection) and a weakness (throws away potential information), in my opinion. Either way, it would be useful to document it.

At some later stage it would also be useful to show that we are robust to selection / demography, I suspect.

**Comment by nspope** [comment]
Being slightly pedantic (but worth clarifying) -- there's a "prior" induced on the internal nodes by the exponential mixture on roots, even though we don't have node-specific coalescent priors. It's really more like regularisation, because we fit the mixture by EM. It's not technically an improper or flat prior, though (just added to documentation).

**Comment by hyanwong** [comment]
Right, but I think of the constraints on internal nodes as being induced by the combination of topology and root priors. If they weren't attached, there would be no constraint.
